import type {Metadata} from "next";

import {Inter} from "next/font/google";
import clsx from "clsx";

import {Header} from "@/components/ui/header";
import {Footer} from "@/components/ui/footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "URL Shortener",
  description: "Generated by appncy",
};

const inter = Inter({subsets: ["latin"]});

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          "pattern-hive-gray-500/20  pattern-hive-scale-50 dark container m-auto grid h-full min-h-screen w-full grid-rows-[auto,1fr,auto] bg-background px-4 font-sans antialiased",
          inter.className,
        )}
      >
        <Header />
        <main className="px-20 py-8">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
